import { Octokit } from '@octokit/rest';

export function getOctokit(accessToken: string) {
  return new Octokit({ auth: accessToken });
}

export async function pushFragmentToGitHub({
  accessToken, owner, repo, files, commitMessage = 'Generated by Isotope',
}: {
  accessToken: string;
  owner: string;
  repo: string;
  files: { [path: string]: string };
  commitMessage?: string;
}) {
  const octokit = getOctokit(accessToken);

  const { data: repoData } = await octokit.repos.get({ owner, repo });
  const branch = repoData.default_branch;

  const { data: refData } = await octokit.git.getRef({ owner, repo, ref: `heads/${branch}` });
  const latestCommitSha = refData.object.sha;

  const { data: commitData } = await octokit.git.getCommit({ owner, repo, commit_sha: latestCommitSha });
  const baseTreeSha = commitData.tree.sha;

  const blobs = await Promise.all(
    Object.entries(files).map(async ([path, content]) => {
      const { data } = await octokit.git.createBlob({
        owner, repo,
        content: Buffer.from(content).toString('base64'),
        encoding: 'base64',
      });
      return { path, sha: data.sha, mode: '100644' as const, type: 'blob' as const };
    }),
  );

  const { data: newTree } = await octokit.git.createTree({ owner, repo, base_tree: baseTreeSha, tree: blobs });
  const { data: newCommit } = await octokit.git.createCommit({
    owner, repo, message: commitMessage, tree: newTree.sha, parents: [latestCommitSha],
  });
  await octokit.git.updateRef({ owner, repo, ref: `heads/${branch}`, sha: newCommit.sha });

  return { commitSha: newCommit.sha, branch };
}

export async function registerGitHubWebhook({
  accessToken, owner, repo, webhookUrl, secret,
}: {
  accessToken: string; owner: string; repo: string; webhookUrl: string; secret: string;
}) {
  const octokit = getOctokit(accessToken);
  const { data } = await octokit.repos.createWebhook({
    owner, repo,
    config: { url: webhookUrl, content_type: 'json', secret },
    events: ['push'],
    active: true,
  });
  return data.id;
}

export async function deleteGitHubWebhook({
  accessToken, owner, repo, hookId,
}: {
  accessToken: string; owner: string; repo: string; hookId: number;
}) {
  const octokit = getOctokit(accessToken);
  await octokit.repos.deleteWebhook({ owner, repo, hook_id: hookId });
}

export async function getRepoFiles({
  accessToken, owner, repo, branch = 'main',
}: {
  accessToken: string; owner: string; repo: string; branch?: string;
}): Promise<{ [path: string]: string }> {
  const octokit = getOctokit(accessToken);

  const { data: refData } = await octokit.git.getRef({ owner, repo, ref: `heads/${branch}` });
  const { data: commitData } = await octokit.git.getCommit({ owner, repo, commit_sha: refData.object.sha });
  const { data: treeData } = await octokit.git.getTree({ owner, repo, tree_sha: commitData.tree.sha, recursive: '1' });

  const files: { [path: string]: string } = {};
  await Promise.all(
    treeData.tree
      .filter((item) => item.type === 'blob' && item.path && item.sha)
      .map(async (item) => {
        const { data: blob } = await octokit.git.getBlob({ owner, repo, file_sha: item.sha! });
        files[item.path!] = Buffer.from(blob.content, 'base64').toString('utf-8');
      }),
  );
  return files;
}

// ── Branch-per-instruction helpers ───────────────────────────────────────────

// Generate a clean branch name from a prompt
export function generateBranchName(prompt: string): string {
  const slug = prompt
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .split(/\s+/)
    .slice(0, 5)
    .join('-')
  const suffix = Math.random().toString(36).slice(2, 7)
  return `isotope/${slug}-${suffix}`
}

// Create a new branch and push files to it
export async function createBranchAndPush({
  accessToken, owner, repo, branchName, files, commitMessage = 'Generated by Isotope',
}: {
  accessToken: string
  owner: string
  repo: string
  branchName: string
  files: { [path: string]: string }
  commitMessage?: string
}) {
  const octokit = getOctokit(accessToken)

  // Get default branch SHA to branch from
  const { data: repoData } = await octokit.repos.get({ owner, repo })
  const defaultBranch = repoData.default_branch

  const { data: refData } = await octokit.git.getRef({ owner, repo, ref: `heads/${defaultBranch}` })
  const latestCommitSha = refData.object.sha

  // Create the new branch
  await octokit.git.createRef({
    owner, repo,
    ref: `refs/heads/${branchName}`,
    sha: latestCommitSha,
  })

  // Push files to the new branch
  const { data: commitData } = await octokit.git.getCommit({ owner, repo, commit_sha: latestCommitSha })
  const baseTreeSha = commitData.tree.sha

  const blobs = await Promise.all(
    Object.entries(files).map(async ([path, content]) => {
      const { data } = await octokit.git.createBlob({
        owner, repo,
        content: Buffer.from(content).toString('base64'),
        encoding: 'base64',
      })
      return { path, sha: data.sha, mode: '100644' as const, type: 'blob' as const }
    }),
  )

  const { data: newTree } = await octokit.git.createTree({ owner, repo, base_tree: baseTreeSha, tree: blobs })
  const { data: newCommit } = await octokit.git.createCommit({
    owner, repo, message: commitMessage, tree: newTree.sha, parents: [latestCommitSha],
  })
  await octokit.git.updateRef({ owner, repo, ref: `heads/${branchName}`, sha: newCommit.sha })

  return { commitSha: newCommit.sha, branchName }
}

// Merge a branch into default branch
export async function mergeBranchToMain({
  accessToken, owner, repo, branchName,
}: {
  accessToken: string
  owner: string
  repo: string
  branchName: string
}) {
  const octokit = getOctokit(accessToken)
  const { data: repoData } = await octokit.repos.get({ owner, repo })

  await octokit.repos.merge({
    owner, repo,
    base: repoData.default_branch,
    head: branchName,
    commit_message: `Merge ${branchName} — via Isotope`,
  })
}

// Delete a branch (discard)
export async function deleteBranch({
  accessToken, owner, repo, branchName,
}: {
  accessToken: string
  owner: string
  repo: string
  branchName: string
}) {
  const octokit = getOctokit(accessToken)
  await octokit.git.deleteRef({ owner, repo, ref: `heads/${branchName}` })
}

// ─────────────────────────────────────────────────────────────────────────────
// FEATURE 7: Smart Diff-Aware GitHub Push
// Only pushes files that actually changed vs the last commit.
// Auto-merges branch if compilation passed.
// Commit messages generated from task summary — not hardcoded.
// ─────────────────────────────────────────────────────────────────────────────

// Get file contents of last commit on a branch
export async function getLastCommitFiles({
  accessToken,
  owner,
  repo,
  branch,
}: {
  accessToken: string
  owner: string
  repo: string
  branch: string
}): Promise<{ [path: string]: string }> {
  const octokit = getOctokit(accessToken)

  try {
    const { data: refData } = await octokit.git.getRef({ owner, repo, ref: `heads/${branch}` })
    const { data: commitData } = await octokit.git.getCommit({ owner, repo, commit_sha: refData.object.sha })
    const { data: treeData } = await octokit.git.getTree({
      owner, repo, tree_sha: commitData.tree.sha, recursive: '1',
    })

    const files: { [path: string]: string } = {}
    await Promise.all(
      treeData.tree
        .filter((item) => item.type === 'blob' && item.path && item.sha)
        .map(async (item) => {
          try {
            const { data: blob } = await octokit.git.getBlob({ owner, repo, file_sha: item.sha! })
            files[item.path!] = Buffer.from(blob.content, 'base64').toString('utf-8')
          } catch {
            // file unreadable — skip
          }
        })
    )
    return files
  } catch {
    return {} // branch doesn't exist yet — all files are new
  }
}

// Diff two file snapshots — returns only changed files
export function diffFiles(
  previousFiles: { [path: string]: string },
  newFiles: { [path: string]: string }
): { changed: { [path: string]: string }; unchanged: string[]; added: string[]; modified: string[] } {
  const changed: { [path: string]: string } = {}
  const unchanged: string[] = []
  const added: string[] = []
  const modified: string[] = []

  for (const [path, content] of Object.entries(newFiles)) {
    if (!(path in previousFiles)) {
      changed[path] = content
      added.push(path)
    } else if (previousFiles[path] !== content) {
      changed[path] = content
      modified.push(path)
    } else {
      unchanged.push(path)
    }
  }

  return { changed, unchanged, added, modified }
}

// Smart push — only changed files, descriptive commit message
export async function smartPushToGitHub({
  accessToken,
  owner,
  repo,
  branchName,
  newFiles,
  taskSummary,
  autoMerge = false,
}: {
  accessToken: string
  owner: string
  repo: string
  branchName: string
  newFiles: { [path: string]: string }
  taskSummary: string
  autoMerge?: boolean
}): Promise<{
  commitSha: string
  branchName: string
  filesChanged: number
  filesUnchanged: number
  merged: boolean
}> {
  const octokit = getOctokit(accessToken)

  // Get what was in the branch before
  const previousFiles = await getLastCommitFiles({ accessToken, owner, repo, branch: branchName })
  const { changed, unchanged, added, modified } = diffFiles(previousFiles, newFiles)

  // Nothing changed — skip push
  if (Object.keys(changed).length === 0) {
    return { commitSha: '', branchName, filesChanged: 0, filesUnchanged: unchanged.length, merged: false }
  }

  // Generate meaningful commit message from task summary
  const summary = taskSummary.replace(/<\/?task_summary>/g, '').trim().slice(0, 72)
  const details = [
    added.length > 0 ? `add ${added.length} file(s)` : '',
    modified.length > 0 ? `update ${modified.length} file(s)` : '',
  ].filter(Boolean).join(', ')

  const commitMessage = `feat: ${summary}\n\n${details}\n\nGenerated by Isotope`

  // Get or create branch
  const { data: repoData } = await octokit.repos.get({ owner, repo })
  const defaultBranch = repoData.default_branch

  let baseSha: string
  try {
    const { data: refData } = await octokit.git.getRef({ owner, repo, ref: `heads/${branchName}` })
    baseSha = refData.object.sha
  } catch {
    // Branch doesn't exist — create from default branch
    const { data: defaultRef } = await octokit.git.getRef({ owner, repo, ref: `heads/${defaultBranch}` })
    baseSha = defaultRef.object.sha
    await octokit.git.createRef({ owner, repo, ref: `refs/heads/${branchName}`, sha: baseSha })
  }

  // Push only changed files
  const { data: commitData } = await octokit.git.getCommit({ owner, repo, commit_sha: baseSha })
  const baseTreeSha = commitData.tree.sha

  const blobs = await Promise.all(
    Object.entries(changed).map(async ([path, content]) => {
      const { data } = await octokit.git.createBlob({
        owner, repo,
        content: Buffer.from(content).toString('base64'),
        encoding: 'base64',
      })
      return { path, sha: data.sha, mode: '100644' as const, type: 'blob' as const }
    })
  )

  const { data: newTree } = await octokit.git.createTree({ owner, repo, base_tree: baseTreeSha, tree: blobs })
  const { data: newCommit } = await octokit.git.createCommit({
    owner, repo, message: commitMessage, tree: newTree.sha, parents: [baseSha],
  })
  await octokit.git.updateRef({ owner, repo, ref: `heads/${branchName}`, sha: newCommit.sha })

  // Auto-merge if requested and compilation passed
  let merged = false
  if (autoMerge) {
    try {
      await octokit.repos.merge({
        owner, repo,
        base: defaultBranch,
        head: branchName,
        commit_message: `Merge ${branchName} — auto-merged by Isotope\n\n${summary}`,
      })
      merged = true
      // Clean up branch after merge
      await octokit.git.deleteRef({ owner, repo, ref: `heads/${branchName}` })
    } catch (e) {
      // Merge conflict or other error — leave branch open
      console.error('Auto-merge failed:', e)
    }
  }

  return {
    commitSha: newCommit.sha,
    branchName,
    filesChanged: Object.keys(changed).length,
    filesUnchanged: unchanged.length,
    merged,
  }
}
